#!/usr/bin/env python3
"""Tests for lks.extract, lks.structure, and the conversion path in lks.ingest.

There is no pytest in this checkout, so this is a runnable script: plain
asserts, one function per property, and a `__main__` block that runs them all
and reports. Run it with

    . scripts/env.sh && $PY tests/test_extract.py

Every test that writes anything writes to a temporary directory. The two
binary fixtures (.docx, .pdf) are generated by their own generators under
tests/fixtures/ so that nothing opaque is committed.

The load-bearing test is `test_corpus_roundtrip`: every corpus document is run
through extraction and structure inference, and the result must segment to the
same clause ids with the same content hashes. A conversion that changes an
existing corpus document is wrong, whatever else it gets right.
"""
from __future__ import annotations

import shutil
import sys
import tempfile
import traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tests" / "fixtures"))

from lks import extract as E                                    # noqa: E402
from lks import ingest as I                                     # noqa: E402
from lks import structure as S                                  # noqa: E402
from lks.model import content_hash                              # noqa: E402
from lks.segment import parse_document                          # noqa: E402

FIX = ROOT / "tests" / "fixtures"
MSA = FIX / "msa-decimal-outline.txt"
POLICY = FIX / "travel-policy-lettered.txt"
CONDUCT = FIX / "code-of-conduct-headings-only.md"
PORTAL = FIX / "records-retention-portal.html"
DOCX = FIX / "staff-handbook.docx"
PDF = FIX / "supplier-terms.pdf"
CORPUS_001 = ROOT / "corpus" / "001-employment-terms-annex-c.md"

_TMP: list[Path] = []


def tmpdir() -> Path:
    d = Path(tempfile.mkdtemp(prefix="lks-test-extract-"))
    _TMP.append(d)
    return d


def ensure_fixtures() -> None:
    """The binary fixtures are generated, not committed as blobs."""
    import make_docx
    import make_pdf

    if not DOCX.exists():
        make_docx.build(DOCX)
    if not PDF.exists():
        make_pdf.build(PDF)


# --- 1. normalisation ------------------------------------------------------


def test_normalise_typography_only():
    raw = ("“Base Hourly Rate” means the Employee’s salary "
           "divided by 2,080 — see £75.50 and 1.25 times …")
    out = E.normalise_text(raw)
    assert '"Base Hourly Rate"' in out, out
    assert "Employee's" in out, out
    assert " " not in out
    # digits, currency and words untouched
    assert "2,080" in out and "£75.50" in out and "1.25 times" in out
    assert "..." in out and "…" not in out
    # em dash is canonicalised, NOT folded to ASCII: folding would edit the text
    assert "—" in out, out
    assert "--" not in out


def test_normalise_is_idempotent_and_keeps_dash_family_canonical():
    raw = "a ‒ b ― c ‑d − e"
    once = E.normalise_text(raw)
    assert once == E.normalise_text(once)
    assert "–" in once and "—" in once      # figure dash, horizontal bar
    assert "‒" not in once and "―" not in once
    assert "-d" in once                               # non-breaking hyphen
    assert E.normalise_text("ofﬁce") == "office"  # PDF ligature restores the word
    assert E.normalise_text("soft­hyphen") == "softhyphen"


def test_paragraph_breaks_preserved_line_breaks_too():
    text = "one line\nstill clause one\n\n  (a) first item;\n  (b) second item.\n"
    paras = E.split_paragraphs(E.normalise_text(text))
    assert len(paras) == 2, [p.text for p in paras]
    assert paras[0].text == "one line\nstill clause one"
    # the sub-paragraph list is ONE paragraph whose lines stay separate
    assert paras[1].lines == ["  (a) first item;", "  (b) second item."]
    assert [p.index for p in paras] == [1, 2]


def test_dehyphenation_only_joins_broken_words():
    assert E._dehyphenate("reason-\nable") == "reasonable"
    assert E._dehyphenate("Client-\nBillable") == "Client-\nBillable"   # capital
    assert E._dehyphenate("pro-rated") == "pro-rated"


# --- 2. formats ------------------------------------------------------------


def test_txt_extraction():
    ex = E.extract(MSA)
    assert ex.fmt == "txt" and ex.n_paras > 20
    assert ex.paras[0].text == "MASTER SERVICES AGREEMENT"
    assert any("WHEREAS the Customer" in p.text for p in ex.paras)


def test_markdown_extraction_types_headings_and_strips_markers():
    ex = E.extract(CORPUS_001)
    heads = [p for p in ex.paras if p.kind == "heading"]
    assert len(heads) == 11 and heads[0].level == 1 and heads[1].level == 2
    # front matter is metadata the format carries, not text
    assert ex.meta["doc_id"] == "EMP-ANNEX-C"
    assert ex.meta["effective_date"] == "2024-01-01"
    assert not any(p.text.startswith("---") for p in ex.paras)
    # `**C-4.2**` becomes `C-4.2`, so a house document takes the same path as
    # any other document rather than a privileged one
    assert any(p.text.startswith("C-4.2 By way of exception") for p in ex.paras)
    assert not any("**" in p.text for p in ex.paras)


def test_docx_extraction_stdlib_only():
    ex = E.extract(DOCX)
    assert ex.fmt == "docx" and ex.tool == "zipfile+ElementTree"
    assert ex.meta["title"] == "Remote Working Standard"
    assert ex.meta["creator"] == "People Operations"
    assert ex.meta["created"].startswith("2025-11-03")
    assert ex.meta["version"] == "2.1"
    # Word's Title style sits above Heading1, so levels are distinguishable
    levels = {p.text: p.level for p in ex.paras if p.kind == "heading"}
    assert levels["Remote Working Standard"] == 1
    assert levels["1. Eligibility"] == 2
    assert levels["Conditions"] == 3
    # automatic list numbering is invisible in the text, and we say so
    assert any("automatic list numbering" in w for w in ex.warnings)
    assert any(p.note == "docx auto-numbered list item" for p in ex.paras)
    assert any("£350" in p.text for p in ex.paras)     # currency survives


def test_docx_that_is_not_a_zip_names_the_remedy():
    bad = tmpdir() / "old.docx"
    bad.write_bytes(b"\xd0\xcf\x11\xe0legacy binary word document")
    try:
        E.extract(bad)
        raise AssertionError("expected ExtractionError")
    except E.ExtractionError as e:
        assert "zip" in str(e) and "libreoffice" in str(e)


def test_pdf_backend_is_probed_not_assumed():
    caps = E.capabilities()["pdf"]
    available = E.pdf_backends()
    assert set(caps["available"]) == set(available)
    assert caps["chosen"] in ("pdftotext", "pypdf", None)
    if available:
        assert caps["remedy"] is None
    # with neither backend present the error names BOTH options
    real = E.pdf_backends
    try:
        E.pdf_backends = lambda: {}
        E.extract(PDF)
        raise AssertionError("expected ExtractionError")
    except E.ExtractionError as e:
        assert "poppler" in str(e) and "pypdf" in str(e)
    finally:
        E.pdf_backends = real


def test_pdf_extraction_isolates_page_furniture():
    if not E.pdf_backends():
        return "skipped: no pdftotext or pypdf on this machine"
    ex = E.extract(PDF)
    assert ex.fmt == "pdf" and ex.tool in ("pdftotext", "pypdf")
    flat = [" ".join(p.text.split()) for p in ex.paras]
    # a footer and the next page's header arrive with no blank line between
    # them; each must end up as its own paragraph so it can be classified
    assert "Page 1 of 3" in flat and "Page 3 of 3" in flat
    assert flat.count("SUPPLIER TERMS OF PURCHASE — CONFIDENTIAL") == 3
    assert any(t.startswith("2.3 Where the Company fails to pay") for t in flat)
    return None


def test_pdf_title_is_not_the_running_header():
    if not E.pdf_backends():
        return "skipped: no pdftotext or pypdf on this machine"
    st = convert(PDF).structured
    # the header of page 1 arrives in the text layer BEFORE the title and
    # looks just like it; taking it would name the document "... CONFIDENTIAL"
    assert st.meta["title"] == "SUPPLIER TERMS OF PURCHASE", st.meta["title"]
    assert "top-level heading" in st.meta_sources["title"]
    return None


def test_html_extraction_strips_tags_and_marks_chrome():
    ex = E.extract(PORTAL)
    assert ex.fmt == "html" and ex.meta["title"].startswith("Records Retention")
    texts = [p.text for p in ex.paras]
    assert not any("<" in t for t in texts)
    assert any(t.startswith('1.2 "Record" means') for t in texts)     # &ldquo;
    assert any("Article 1 – Scope" == t for t in texts)          # &ndash;
    assert not any("analytics" in t for t in texts)                   # <script>
    chrome = [p for p in ex.paras if p.kind == "furniture"]
    assert {" ".join(p.text.split()) for p in chrome} == {
        "All policies", "© Acme Holdings Limited"}, chrome


def test_unsupported_formats_say_what_is_missing():
    for suffix, needle in ((".doc", "libreoffice"), (".rtf", "RTF"),
                           (".xlsx", "spreadsheet")):
        f = tmpdir() / f"x{suffix}"
        f.write_bytes(b"x")
        try:
            E.extract(f)
            raise AssertionError(f"expected refusal for {suffix}")
        except E.ExtractionError as e:
            assert needle in str(e), (suffix, str(e))
    odd = tmpdir() / "policy.xyz"
    odd.write_text("text")
    try:
        E.extract(odd)
        raise AssertionError("expected refusal")
    except E.ExtractionError as e:
        assert ".docx" in str(e) and ".pdf" in str(e)


def test_flat_text_without_blank_lines_is_resplit_and_flagged():
    lines = ["MASTER TERMS"] + [
        f"{i}.1 The Supplier shall do thing number {i} without delay."
        for i in range(1, 12)]
    paras, inferred = E.paragraphs_from_flat_text("\n".join(lines))
    assert inferred is True
    assert len(paras) == 12, [p.text for p in paras]
    # and where blank lines DO exist they are used as-is, nothing inferred
    paras2, inferred2 = E.paragraphs_from_flat_text("a\n\nb\n\nc")
    assert inferred2 is False and len(paras2) == 3


# --- 3. scheme detection ---------------------------------------------------


def test_scheme_decimal_outline_with_recitals():
    sc = S.detect_scheme(E.extract(MSA))
    assert sc.clause_layer == "decimal"
    assert sc.name == "decimal-outline+recitals"
    ev = sc.evidence
    assert ev["marker_counts"]["decimal"] == 18, ev["marker_counts"]
    assert ev["decimal_depths"] == [2, 3]
    assert "non-decreasing" in ev["why"]


def test_scheme_lettered_policy():
    sc = S.detect_scheme(E.extract(POLICY))
    assert sc.clause_layer == "lettered", sc
    assert sc.section_layer == "numbered"
    assert sc.evidence["marker_counts"]["decimal"] == 0
    assert "none opens with a decimal number" in sc.evidence["why"]


def test_scheme_headings_only():
    sc = S.detect_scheme(E.extract(CONDUCT))
    assert sc.clause_layer == "paragraph" and sc.section_layer == "heading"
    assert sc.name == "headings-only"
    assert "must be synthesised" in sc.evidence["why"]


def test_scheme_article_sections():
    sc = S.detect_scheme(E.extract(PORTAL))
    assert sc.section_layer == "article" and sc.clause_layer == "decimal"


def test_decimal_marker_is_not_an_amount():
    """`1.25 times the Base Hourly Rate` is prose, not clause 1.25."""
    assert S._marker(E.Para(1, "1.25 times the Base Hourly Rate applies."))[0] == "none"
    assert S._marker(E.Para(1, "4.2 By way of exception to 4.1, the rate is"))[0] \
        == "decimal"
    assert S._marker(E.Para(1, "2. Charges and Payment"))[0] == "numbered"
    assert S._marker(E.Para(1, "(b) Tier 2 city: £55 per Travel Day;"))[0] \
        == "lettered"
    assert S._marker(E.Para(1, "Article 7 Indemnity"))[0] == "article"
    assert S._marker(E.Para(1, "WHEREAS the Customer wishes"))[0] == "recital"
    assert S._marker(E.Para(1, "IN WITNESS WHEREOF the parties"))[0] == "execution"


def test_roman_and_letter_ambiguity_resolved_by_sequence():
    assert S._letter_ordinal("i", 0) == (1, "roman")        # first item: roman one
    assert S._letter_ordinal("i", 8) == (9, "letter")       # after (h): the letter
    assert S._letter_ordinal("iii", 2) == (3, "roman")
    assert S._letter_ordinal("c", 2) == (3, "letter")       # not roman 100


# --- 4. structure inference ------------------------------------------------


def flat(text: str) -> str:
    return " ".join(text.split())


def convert(path, out=None, **kw):
    return S.convert_file(path, out_dir=out or tmpdir(), overrides=kw or None)


def test_document_numbering_becomes_the_clause_id():
    st = convert(MSA).structured
    by_id = {c.clause_id: c for c in st.clauses}
    assert by_id["CL-4.2.1"].id_source == "document"
    assert by_id["CL-4.2.1"].document_number == "4.2.1"
    assert by_id["CL-2.1"].id_source == "document"
    assert not by_id["CL-2.1"].synthesised
    # sections come from the document's own numbering, titled by its headings
    assert by_id["CL-2.1"].section_id == "CL-2"
    assert by_id["CL-2.1"].section_title == "CHARGES AND PAYMENT"


def test_lettered_items_stay_inside_their_parent_clause():
    """Splitting `(a) Scheduled Maintenance` out of its clause would detach it
    from the sentence that gives it legal force -- the rule lks.segment states
    for the corpus, applied to an inferred document."""
    st = convert(MSA).structured
    c = next(c for c in st.clauses if c.clause_id == "CL-3.3")
    assert "Excluded Minutes" in c.body
    assert "(a) Scheduled Maintenance" in c.body
    assert "(c) a Force Majeure Event." in c.body
    assert not any(x.clause_id.startswith("CL-3.3.") for x in st.clauses)
    assert any(d.kind == "subparagraph" for d in st.dispositions)


def test_lettered_policy_letters_become_clauses():
    st = convert(POLICY).structured
    by_id = {c.clause_id: c for c in st.clauses}
    assert by_id["CL-3.1"].document_number == "3(a)"
    assert by_id["CL-3.1"].id_source == "derived"          # citable as 3(a)
    assert "subsistence allowance of GBP 45" in flat(by_id["CL-3.1"].body)
    assert by_id["CL-3.2"].document_number == "3(b)"
    # the nested romans under 2(c) stay with their parent
    assert "(i) economy class" in flat(by_id["CL-2.3"].body)
    assert "(iii) business class" in flat(by_id["CL-2.3"].body)


def test_numbered_clauses_without_decimals():
    """`7. The Supplier shall ...` -- the number is the clause's, and the
    house convention's section-relative id keeps it citable as "7"."""
    f = tmpdir() / "purchase-conditions.txt"
    f.write_text(
        "PURCHASE CONDITIONS\n\n"
        "1. The Supplier shall deliver the Goods to the address in the Order.\n\n"
        "2. The Company shall pay each invoice within 30 days of receipt.\n\n"
        "3. Where the Supplier delivers late, the Company may reject the Goods\n"
        "and recover any pre-payment.\n\n"
        "4. Either party may terminate on 30 days' written notice.\n"
    )
    conv = convert(f)
    st = conv.structured
    assert st.scheme.clause_layer == "numbered", st.scheme
    assert st.scheme.name == "numbered-clauses"
    assert [c.clause_id for c in st.clauses] == ["CL-1.1", "CL-2.1", "CL-3.1", "CL-4.1"]
    assert [c.document_number for c in st.clauses] == ["1", "2", "3", "4"]
    assert all(c.id_source == "derived" for c in st.clauses)
    assert all(not c.synthesised for c in st.clauses)
    assert st.meta["title"] == "PURCHASE CONDITIONS"
    doc = parse_document(conv.converted_path)
    assert doc.clause("CL-3.1").body.startswith("Where the Supplier delivers late")


def test_headings_only_ids_are_synthesised_and_positional():
    st = convert(CONDUCT).structured
    ids = [c.clause_id for c in st.clauses]
    assert "P-3.2" in ids
    p32 = next(c for c in st.clauses if c.clause_id == "P-3.2")
    # "the second paragraph under the third heading"
    assert p32.section_title == "Environmental standards"
    assert p32.body.startswith("A supplier must report any spill")
    assert p32.synthesised and p32.id_source == "synthesised"
    assert p32.document_number == ""
    assert "CANNOT be cited" in p32.note
    assert all(c.synthesised for c in st.clauses)


def test_recitals_and_execution_are_kept_apart():
    st = convert(MSA).structured
    recitals = [c for c in st.clauses if c.section_id == "R-1"]
    assert len(recitals) == 3 and recitals[0].body.startswith("WHEREAS")
    assert all(c.synthesised for c in recitals)
    ex = [c for c in st.clauses if c.section_id == "EX-1"]
    assert len(ex) == 1 and ex[0].body.startswith("IN WITNESS WHEREOF")
    # the execution block is last, not filed under the recitals at the top
    assert st.clauses[-1].clause_id == "EX-1.1"


def test_a_heading_ends_the_clause_above_it():
    """A paragraph under a new heading must not be appended to the last clause
    of the previous section: that moves text silently."""
    st = convert(DOCX).structured
    assert [c.clause_id for c in st.clauses][:5] == [
        "P-0.1", "CL-1.1", "CL-1.2", "CL-2.1", "CL-2.2"]
    cond = [c for c in st.clauses if c.section_title == "Conditions"]
    assert [c.clause_id for c in cond] == ["P-3.1", "P-3.2"], cond
    assert all(c.synthesised for c in cond)
    assert "36-month period" in cond[0].body
    assert "36-month period" not in \
        next(c for c in st.clauses if c.clause_id == "CL-2.2").body


def test_page_furniture_is_excluded_but_never_lost():
    if not E.pdf_backends():
        return "skipped: no pdftotext or pypdf on this machine"
    conv = convert(PDF)
    st = conv.structured
    assert len(st.furniture) == 6, [d.index for d in st.furniture]
    body = "\n".join(c.body for c in st.clauses)
    assert "Page 1 of 3" not in body and "CONFIDENTIAL" not in body
    report = conv.report_path.read_text()
    for d in st.furniture:
        assert d.text in report                      # verbatim, not truncated
    assert "could not confidently assign" in report
    return None


def test_every_source_paragraph_is_accounted_for():
    for src in (MSA, POLICY, CONDUCT, PORTAL, DOCX, PDF, CORPUS_001):
        if src == PDF and not E.pdf_backends():
            continue
        conv = convert(src)
        st = conv.structured
        indexes = [d.index for d in st.dispositions]
        assert sorted(indexes) == [p.index for p in st.extracted.paras], src
        assert len(indexes) == len(set(indexes)), src          # exactly once
        report = conv.report_path.read_text()
        assert f"({st.extracted.n_paras} of {st.extracted.n_paras} accounted for)" \
            in report, src
        for d in st.dispositions:
            assert f"| {d.index} | {d.kind} |" in report, (src, d.index)


def test_accounting_failure_is_a_crash_not_a_quiet_omission():
    ex = E.extract(POLICY)
    real = S._Builder.run

    def broken(self):
        clauses, disp, warn = real(self)
        return clauses, disp[:-1], warn            # "lose" one paragraph

    try:
        S._Builder.run = broken
        S.infer_structure(ex)
        raise AssertionError("expected AssertionError about accounting")
    except AssertionError as e:
        assert "accounting is broken" in str(e), e
    finally:
        S._Builder.run = real


def test_duplicate_document_numbering_is_disambiguated_and_flagged():
    f = tmpdir() / "dupes.txt"
    f.write_text(
        "SAMPLE TERMS\n\n"
        "1. CHARGES\n\n"
        "1.1 The Customer shall pay the first amount.\n\n"
        "1.2 The Customer shall pay the second amount.\n\n"
        "1.2 The Customer shall pay a third amount under a repeated number.\n\n"
        "1.3 The Customer shall pay the fourth amount.\n"
    )
    st = convert(f).structured
    ids = [c.clause_id for c in st.clauses]
    assert ids == ["CL-1.1", "CL-1.2", "CL-1.2.1", "CL-1.3"], ids
    dup = next(c for c in st.clauses if c.clause_id == "CL-1.2.1")
    assert dup.synthesised and "more than once" in dup.note


def test_unassignable_paragraph_is_surfaced_not_dropped():
    f = tmpdir() / "orphan.txt"
    f.write_text(
        "STRAY SUB-PARAGRAPH POLICY\n\n"
        "(a) This sub-paragraph appears before any clause exists;\n\n"
        "(b) So does this one, and neither has a parent clause.\n\n"
        "(c) And this one, which must not be mistaken for a copyright line.\n\n"
        "(d) And this.\n"
    )
    ex = E.extract(f)
    # read with the decimal scheme, under which a lettered paragraph is a
    # sub-paragraph -- and here there is no clause above it to belong to
    st = S._Builder(ex, S.Scheme("decimal-outline", "heading", "decimal", {"why": ""}))
    clauses, disp, _ = st.run()
    orphans = [d for d in disp if d.kind == "unassigned"]
    assert len(orphans) == 4, [d.kind for d in disp]
    assert "no clause for it to belong to" in orphans[0].reason
    assert orphans[0].text.startswith("(a) This sub-paragraph")


# --- 5. metadata: derive what you can, never invent a date -----------------


def test_effective_date_comes_from_effective_date_context():
    st = convert(MSA).structured
    # "made on 14 March 2025 and takes effect from 1 April 2025"
    assert st.meta["effective_date"] == "2025-04-01"
    assert "takes effect from" in st.meta_sources["effective_date"]
    assert any("execution or signature date" in w and "2025-03-14" in w
               for w in st.warnings), st.warnings


def test_effective_date_is_never_invented():
    conv = convert(CONDUCT)
    st = conv.structured
    assert st.meta["effective_date"] == S.NEEDS_HUMAN
    assert "effective_date" in st.needs_human
    assert "--effective-date" in st.needs_human["effective_date"]
    report = conv.report_path.read_text()
    assert "A HUMAN MUST SUPPLY THIS" in report
    # title and doc_id ARE derivable from the document and the file name
    assert st.meta["title"] == "Supplier Code of Conduct"
    assert st.meta["doc_id"] == "CODE-OF-CONDUCT-HEADINGS-ONLY"
    assert "top-level heading" in st.meta_sources["title"]
    assert "file name" in st.meta_sources["doc_id"]


def test_conflicting_effective_dates_are_not_chosen_between():
    f = tmpdir() / "two-dates.txt"
    f.write_text(
        "AMENDED POLICY\n\n"
        "1. SCOPE\n\n"
        "1.1 This Policy is effective from 1 March 2025 in respect of new "
        "Employees.\n\n"
        "1.2 This Policy takes effect on 1 July 2025 in respect of existing "
        "Employees.\n"
    )
    st = convert(f).structured
    assert st.meta["effective_date"] == S.NEEDS_HUMAN
    assert any("DIFFERENT dates" in w for w in st.warnings), st.warnings


def test_ambiguous_numeric_date_is_not_interpreted():
    f = tmpdir() / "ambiguous.txt"
    f.write_text("SAMPLE\n\n1. SCOPE\n\n1.1 This Policy is effective from "
                 "03/04/2025 for all staff.\n")
    st = convert(f).structured
    assert st.meta["effective_date"] == S.NEEDS_HUMAN
    assert any("ambiguous numeric date" in w for w in st.warnings), st.warnings


def test_hand_supplied_metadata_is_recorded_as_such():
    st = convert(CONDUCT, doc_id="SUP-COC", effective_date="2026-04-01",
                 owner="Procurement").structured
    assert st.needs_human == {}
    assert st.meta["doc_id"] == "SUP-COC"
    assert st.meta["effective_date"] == "2026-04-01"
    assert st.meta_sources["effective_date"] == "supplied by hand"
    assert st.meta["owner"] == "Procurement"
    assert st.meta["version"] == S.UNKNOWN          # unknown, but not blocking


def test_docx_core_properties_fill_the_front_matter():
    st = convert(DOCX).structured
    assert st.meta["title"] == "Remote Working Standard"
    assert st.meta["owner"] == "People Operations"
    assert st.meta["version"] == "2.1"
    assert st.meta["effective_date"] == "2026-02-01"      # from the text
    assert any("file timestamp" in w for w in st.warnings)


# --- 6. the converted document is the house convention --------------------


def test_converted_documents_segment_under_the_house_convention():
    for src in (MSA, POLICY, CONDUCT, PORTAL, DOCX, PDF):
        if src == PDF and not E.pdf_backends():
            continue
        conv = convert(src, effective_date="2026-01-01")
        doc = parse_document(conv.converted_path)
        assert doc.clauses, src
        assert len(doc.clauses) == len(conv.structured.clauses), src
        for c, inferred in zip(doc.clauses, conv.structured.clauses):
            assert c.clause_id == inferred.clause_id, src
            assert content_hash(c.body) == content_hash(inferred.body), (src, c.ref)
            assert c.clause_id.startswith(c.section_id + "."), (src, c.ref)


def test_corpus_roundtrip_is_identical():
    """THE acceptance test: a corpus document must come back unchanged."""
    out = tmpdir()
    docs = sorted((ROOT / "corpus").glob("*.md"))
    assert docs, "no corpus documents found"
    for path in docs:
        before = parse_document(path)
        conv = S.convert_file(path, out_dir=out)
        after = parse_document(conv.converted_path)
        assert [c.clause_id for c in after.clauses] == \
               [c.clause_id for c in before.clauses], path.name
        assert {c.clause_id: c.hash for c in after.clauses} == \
               {c.clause_id: c.hash for c in before.clauses}, path.name
        assert {(c.section_id, c.section_title) for c in after.clauses} == \
               {(c.section_id, c.section_title) for c in before.clauses}, path.name
        for field_ in ("doc_id", "title", "version", "effective_date",
                       "jurisdiction", "owner"):
            assert getattr(after, field_) == getattr(before, field_), (path, field_)
        st = conv.structured
        assert st.synthesised == [] and st.unassigned == [], path.name
    # and the headline number from the brief
    first = parse_document(
        S.convert_file(CORPUS_001, out_dir=out).converted_path)
    assert len(first.clauses) == 26
    assert first.clause("C-7.2").hash == \
        parse_document(CORPUS_001).clause("C-7.2").hash


def test_report_states_provenance_for_every_clause():
    conv = convert(MSA)
    report = conv.report_path.read_text()
    for c in conv.structured.clauses:
        assert f"| `{c.clause_id}` |" in report, c.clause_id
    assert "| **synthesised** |" in report
    assert "| document |" in report
    assert "How the scheme was chosen" in report
    assert "decimal-outline+recitals" in report


# --- 7. ingestion: converted, recorded, and still gated -------------------


def isolated_ingest():
    """propose_ingestion with its proposals and conversions in a temp dir."""
    d = tmpdir()
    real = I.PROPOSALS
    I.PROPOSALS = d / "proposals"
    return d, real


def test_ingest_accepts_a_real_format_and_records_the_conversion():
    d, real = isolated_ingest()
    try:
        pr = I.propose_ingestion(PDF if E.pdf_backends() else MSA,
                                 converted_dir=d / "converted")
        assert pr.conversion is not None
        assert pr.original_path == str(PDF if E.pdf_backends() else MSA)
        # the CONVERTED file is the document of record from here on
        assert pr.source_path == pr.conversion["converted_path"]
        assert Path(pr.source_path).suffix == ".md"
        assert Path(pr.conversion["report_path"]).exists()
        assert pr.triage and len(pr.triage) == pr.conversion["n_clauses"]
        assert any("not in the house convention" in n for n in pr.notes)
        assert (pr.dir / "proposal.yaml").exists()
        again = I.Proposal.load(pr.id)                 # survives a round trip
        assert again.conversion["scheme"] == pr.conversion["scheme"]
        assert again.original_path == pr.original_path
    finally:
        I.PROPOSALS = real


def test_ingest_of_a_house_document_is_unchanged():
    d, real = isolated_ingest()
    try:
        pr = I.propose_ingestion(CORPUS_001, converted_dir=d / "converted")
        assert pr.conversion is None
        assert pr.source_path == str(CORPUS_001)
        assert not (d / "converted").exists()          # nothing converted
        assert len(pr.triage) == 26
        # the existing detectors still fire on the existing corpus document
        kinds = {c.kind for c in pr.conflicts}
        assert I.ConflictKind.DOC_COLLISION not in kinds   # same content
        assert I.ConflictKind.DUPLICATE_ENCODING in kinds  # already encoded
    finally:
        I.PROPOSALS = real


def test_conversion_gaps_become_conflicts_and_block_the_merge():
    d, real = isolated_ingest()
    try:
        pr = I.propose_ingestion(CONDUCT, converted_dir=d / "converted")
        kinds = {c.kind: c for c in pr.conflicts}
        assert I.ConflictKind.CONVERSION_METADATA in kinds
        assert kinds[I.ConflictKind.CONVERSION_METADATA].severity == "blocking"
        assert I.ConflictKind.CONVERSION_SYNTHESISED in kinds
        assert kinds[I.ConflictKind.CONVERSION_SYNTHESISED].severity == "advisory"
        assert not pr.mergeable and pr.unresolved
        try:
            I.merge(pr.id, corpus_dir=str(d / "corpus"))
            raise AssertionError("merge must refuse while a conflict is unresolved")
        except I.MergeRefused as e:
            assert "unresolved conflict" in str(e)
            assert "resolution" in str(e) and "resolved_by" in str(e)

        # resolving the conflict is not enough: the sentinel is still in the file
        for c in pr.conflicts:
            c.resolution = "reviewed"
            c.resolved_by = "tester"
        pr.save()
        assert I.Proposal.load(pr.id).mergeable
        try:
            I.merge(pr.id, corpus_dir=str(d / "corpus"))
            raise AssertionError("merge must refuse on the NEEDS-HUMAN sentinel")
        except I.MergeRefused as e:
            assert S.NEEDS_HUMAN in str(e)
            assert "not clearable by a resolution" in str(e)
    finally:
        I.PROPOSALS = real


def test_merge_proceeds_once_a_human_supplies_what_was_missing():
    d, real = isolated_ingest()
    try:
        corpus = d / "corpus"
        corpus.mkdir()
        pr = I.propose_ingestion(CONDUCT, converted_dir=d / "converted",
                                 overrides={"doc_id": "SUP-COC",
                                            "effective_date": "2026-04-01",
                                            "version": "1.0",
                                            "jurisdiction": "England and Wales",
                                            "owner": "Procurement"},
                                 corpus_dir=str(corpus))
        assert not any(c.kind == I.ConflictKind.CONVERSION_METADATA
                       for c in pr.conflicts)
        for c in pr.blocking:
            c.resolution = "reviewed: synthesised ids confirmed by counsel"
            c.resolved_by = "tester"
        pr.save()
        result = I.merge(pr.id, corpus_dir=str(corpus))
        merged = Path(result["corpus"])
        assert merged.exists() and merged.parent == corpus
        doc = parse_document(merged)
        assert doc.doc_id == "SUP-COC" and doc.effective_date == "2026-04-01"
        assert len(doc.clauses) == 11
    finally:
        I.PROPOSALS = real


def test_merge_gate_survives_for_ordinary_conflicts():
    """The gate itself is untouched: a blocking conflict with no resolution
    refuses, and one with a resolution and a resolver does not."""
    d, real = isolated_ingest()
    try:
        corpus = d / "corpus"
        corpus.mkdir()
        src = d / "doc.md"
        shutil.copy(CORPUS_001, src)
        pr = I.Proposal(id="gate-test", source_path=str(src), doc_id="X",
                        title="t", created="2026-01-01")
        pr.conflicts = [I.Conflict(kind=I.ConflictKind.NUMERIC_DIVERGENCE,
                                   incoming_ref="X 1.1", detail="a divergence")]
        pr.save()
        try:
            I.merge("gate-test", corpus_dir=str(corpus))
            raise AssertionError("merge must refuse")
        except I.MergeRefused:
            pass
        pr.conflicts[0].resolution = "the incoming figure supersedes"
        pr.conflicts[0].resolved_by = "counsel"
        pr.save()
        out = I.merge("gate-test", corpus_dir=str(corpus))
        assert Path(out["corpus"]).exists()
    finally:
        I.PROPOSALS = real


TESTS = [v for k, v in sorted(globals().items()) if k.startswith("test_")]


def main() -> int:
    ensure_fixtures()
    failed: list[tuple[str, str]] = []
    skipped: list[str] = []
    for fn in TESTS:
        try:
            note = fn()
            if note:
                skipped.append(f"{fn.__name__}: {note}")
                print(f"skip {fn.__name__}  ({note})")
            else:
                print(f"ok   {fn.__name__}")
        except Exception:
            failed.append((fn.__name__, traceback.format_exc()))
            print(f"FAIL {fn.__name__}")
    for d in _TMP:
        shutil.rmtree(d, ignore_errors=True)
    print()
    for name, tb in failed:
        print(f"--- {name} ---\n{tb}")
    print(f"{len(TESTS) - len(failed) - len(skipped)} passed, {len(skipped)} skipped, "
          f"{len(failed)} failed, of {len(TESTS)} tests")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
